# Generated by Django 5.0.4 on 2024-04-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('rating', models.CharField(choices=[('A', 'A (Todo público)'), ('B', 'B (Mayores de 13 años)'), ('C', 'C (Mayores de 18 años)')], max_length=1, verbose_name='clasificación')),
                ('running_time', models.IntegerField(blank=True, default='', verbose_name='duración')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='fecha de estreno')),
                ('poster', models.URLField(blank=True, default='', verbose_name='poster')),
                ('backdrop', models.URLField(blank=True, default='', verbose_name='fondo')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'cine',
                'verbose_name_plural': 'cines',
            },
        ),
    ]
