# Generated by Django 5.0.4 on 2024-04-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('rating', models.CharField(choices=[('A', 'A (Todo público)'), ('B', 'B (Mayores de 13 años)'), ('C', 'C (Mayores de 18 años)')], max_length=1, verbose_name='clasificación')),
                ('running_time', models.IntegerField(blank=True, default='', verbose_name='duración (en minutos)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='fecha de estreno')),
                ('poster', models.URLField(blank=True, default='', verbose_name='poster')),
                ('backdrop', models.URLField(blank=True, default='', verbose_name='fondo')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
            },
        ),
        migrations.RenameModel(
            old_name='Theater',
            new_name='Theatre',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
