# Generated by Django 5.0.4 on 2024-04-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_rename_theater_theatre_delete_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(blank=True, null=True, verbose_name='fondo'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True, verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='duración (en minutos)'),
        ),
    ]
