# Generated by Django 5.0.4 on 2024-04-05 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_movie_name_movie_original_name_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(default='none', verbose_name='fondo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_name',
            field=models.CharField(default='none', max_length=255, verbose_name='título original'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default='none', verbose_name='resumen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='none', verbose_name='poster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, choices=[('A', 'A (Todo público)'), ('B', 'B (Mayores de 13 años)'), ('C', 'C (Mayores de 18 años)')], max_length=1, null=True, verbose_name='clasificación'),
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium', models.IntegerField(verbose_name='sala')),
                ('time', models.DateTimeField(verbose_name='hora')),
                ('format', models.CharField(choices=[('digital', 'Digital'), ('3D', '3D')], default='Digital', max_length=30, verbose_name='formato')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='Español', max_length=30, verbose_name='idioma')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theatre')),
            ],
        ),
    ]
