# Generated by Django 5.0.4 on 2024-04-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_backdrop_alter_movie_original_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'verbose_name': 'función', 'verbose_name_plural': 'funciones'},
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie', verbose_name='Película'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theatre', verbose_name='Cine'),
        ),
    ]
