# Generated by Django 5.0.4 on 2024-05-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_showtime_options_alter_showtime_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='original_name',
            new_name='original_title',
        ),
    ]
